version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/deploy-docs
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      github-actions:
        patterns: ["*"]
        update-types: [minor, patch]
      github-actions-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0
    groups:
      npm-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
      npm-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /apps/web-app
    schedule:
      interval: weekly
    groups:
      docker-minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    ignore:
      - dependency-name: node
        update-types: ["version-update:semver-major"]
