import type { Credit, ScanScope, TraceStep } from "@scoutui/scan-format";
import { z } from "zod";

// ---- Identity enums (referenced across summary + detail shapes) ----
export const ComponentScope = z.enum(["external", "local"]);
export type ComponentScope = z.infer<typeof ComponentScope>;
export const ComponentKind = z.enum(["custom-element", "react-component", "vue-component", "tag"]);
export type ComponentKind = z.infer<typeof ComponentKind>;
// Mirrors the scan file `Component`'s `usage` (`@scoutui/scan-format`): why a component
// is in the inventory. Precedence: direct > root > none.
export const UsageKind = z.enum(["direct", "root", "none"]);
export type UsageKind = z.infer<typeof UsageKind>;

// Framework breakdown for a repo: one entry per component `kind` present,
// sorted by count desc.
export const FrameworkCountSchema = z.object({
  kind: ComponentKind,
  count: z.number().int().nonnegative(),
});
export type FrameworkCount = z.infer<typeof FrameworkCountSchema>;

// ---- Tags (web-authored package grouping) ----
export const TagRuleSchema = z.object({
  glob: z.array(z.string()).default([]),   // ["@example/*"]
  exact: z.array(z.string()).default([]),  // ["legacy-design-system"]
});
export type TagRule = z.infer<typeof TagRuleSchema>;

export const TAG_COLOURS = ["teal", "violet", "blue", "berry", "orchid"] as const;
export const TagColourSchema = z.enum(TAG_COLOURS);
export type TagColour = z.infer<typeof TagColourSchema>;

export const TagSchema = z.object({
  id: z.string(),
  value: z.string(),                       // "core", "legacy"
  category: z.string().nullable(),         // "library"; null = plain flat label
  color: TagColourSchema,
  rule: TagRuleSchema,
});
export type Tag = z.infer<typeof TagSchema>;

// Create-or-update payload: id optional (generated by the driver on create).
export const TagInputSchema = TagSchema.partial({ id: true });
export type TagInput = z.infer<typeof TagInputSchema>;

export const TagRefSchema = z.object({
  id: z.string(),
  value: z.string(),
  category: z.string().nullable(),
  color: TagColourSchema,
});
export type TagRef = z.infer<typeof TagRefSchema>;

// ---- Scan diff (what moved between a scan and the one before it) ----
// Keyed by component id; unchanged rows are absent from `marks`. A component is
// added (new in this scan), removed (gone since the previous one) or changed (a
// different occurrence count, carried as `delta`).
export const DiffMarkSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("added") }),
  z.object({ kind: z.literal("removed") }),
  z.object({ kind: z.literal("changed"), delta: z.number().int() }),
]);
export type DiffMark = z.infer<typeof DiffMarkSchema>;

// A previous-scan component absent now. Enough to render an unlinked
// ghost row: identity words, the previous occurrence total, and whether it was
// deprecated.
export const RemovedComponentSchema = z.object({
  componentId: z.string(),
  displayName: z.string(),
  packageName: z.string().nullable(),
  scope: ComponentScope,
  kind: ComponentKind,
  occurrenceCount: z.number().int().nonnegative(),
  deprecated: z.boolean(),
  // Resolved with resolveTags from the vanished component's package, never
  // copied from a live row's tags.
  tags: z.array(TagRefSchema),
});
export type RemovedComponent = z.infer<typeof RemovedComponentSchema>;

export const ScanDiffSchema = z.object({
  baselineScanId: z.string(),
  // The baseline scan's commit date, so the masthead can say when "last scan" was.
  baselineCommittedAt: z.string(),
  marks: z.record(z.string(), DiffMarkSchema),
  added: z.number().int().nonnegative(),
  removed: z.number().int().nonnegative(),
  changed: z.number().int().nonnegative(),
  removedRows: z.array(RemovedComponentSchema),
  deprecatedPrev: z.number().int().nonnegative(),
  deprecatedNow: z.number().int().nonnegative(),
});
export type ScanDiff = z.infer<typeof ScanDiffSchema>;

// The launchpad's per-row read: counts of components added / removed /
// changed (occurrence count moved), and the signed movement of the
// deprecated-in-use count.
export const RepoDeltaSchema = z.object({
  added: z.number().int().nonnegative(),
  removed: z.number().int().nonnegative(),
  changed: z.number().int().nonnegative(),
  deprecated: z.number().int(),
});
export type RepoDelta = z.infer<typeof RepoDeltaSchema>;

// ---- Repo summary (list rows) ----
export const RepoSummarySchema = z.object({
  repoId: z.string(),
  gitRemote: z.string().nullable(),
  branch: z.string().nullable(),
  commit: z.string(),
  committedAt: z.string(),              // ISO commit date of the latest scan
  scanCount: z.number().int().positive(),
  componentCount: z.number().int().nonnegative(),
  externalComponentCount: z.number().int().nonnegative(),
  localComponentCount: z.number().int().nonnegative(),
  packageCount: z.number().int().nonnegative(),
  deprecatedCount: z.number().int().nonnegative(),
  totalOccurrences: z.number().int().nonnegative(),
  frameworkCounts: z.array(FrameworkCountSchema),
  // Newest scan vs the one before (scan-diff seam); null with a single scan.
  delta: RepoDeltaSchema.nullable(),
});
export type RepoSummary = z.infer<typeof RepoSummarySchema>;

// ---- Repo detail (one repo full page payload) ----
export const RepoDetailSchema = RepoSummarySchema.extend({
  initialCommit: z.string().nullable(),
  scanId: z.string(),
  // When the dashboard received the shown scan.
  arrivedAt: z.string(),
  scannerVersion: z.string(),
  // The shown scan vs the scan immediately before it; null on a first scan.
  diff: ScanDiffSchema.nullable(),
  // What the shown scan covered; null for a scan that doesn't record it.
  scope: z.custom<ScanScope>().nullable(),
});
export type RepoDetail = z.infer<typeof RepoDetailSchema>;

// ---- Scan summary (StorageDriver.listScans) ----
export const ScanSummarySchema = z.object({
  scanId: z.string(),
  committedAt: z.string(),
  arrivedAt: z.string(),
  commit: z.string(),
  branch: z.string().nullable(),
  // The signed-in user who uploaded the scan; null when none is recorded, as for an upload with the CI key.
  uploadedBy: z.object({ name: z.string().nullable(), email: z.string() }).nullable(),
  // Whether pages can show the scan's data.
  ready: z.boolean(),
});
export type ScanSummary = z.infer<typeof ScanSummarySchema>;

// ---- Dashboards (saved cohort charts) ----

// Semantic series role. `deprecated` is derived from the governance records that
// cover the cohort at projection time (never authored); `successor` is carried on a derived config's
// selector, because re-projecting a bare DashboardConfig can't know which cohort
// succeeds which. web-shared never emits CSS: a renderer gives each role its own
// fixed colour, which wins over a tag's colour.
export const CohortRoleSchema = z.enum(["deprecated", "successor"]);
export type CohortRole = z.infer<typeof CohortRoleSchema>;

// A cohort: a selector that resolves to a set of components. The engine is blind
// to which kind produced a resolved set. `component` carries an optional display
// label (auto-derived otherwise, see cohortIdentity). `tag` and `package` support
// `deprecatedOnly` to narrow the cohort to deprecated components only.
export const CohortSelectorSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("tag"), tagId: z.string(), deprecatedOnly: z.boolean().optional() }),
  z.object({ kind: z.literal("package"), packageName: z.string(), deprecatedOnly: z.boolean().optional(), role: z.literal("successor").optional() }),
  z.object({ kind: z.literal("component"), componentId: z.string(), label: z.string().optional(), role: z.literal("successor").optional() }),
  z.object({ kind: z.literal("local") }),
]);
export type CohortSelector = z.infer<typeof CohortSelectorSchema>;

export const ChartTypeSchema = z.enum(["trend", "bars", "stacked-share", "table"]);
export type ChartType = z.infer<typeof ChartTypeSchema>;

export const DashboardMetricSchema = z.enum(["count", "share"]);
export type DashboardMetric = z.infer<typeof DashboardMetricSchema>;

// How far back a chart over time reaches from its latest scan.
export const ChartRangeSchema = z.enum(["3m", "6m", "1y", "all"]);
export type ChartRange = z.infer<typeof ChartRangeSchema>;

export const DashboardScopeSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("all") }),
  z.object({ kind: z.literal("repo"), repoId: z.string() }),
]);
export type DashboardScope = z.infer<typeof DashboardScopeSchema>;

export const DashboardConfigSchema = z.object({
  scope: DashboardScopeSchema,
  cohorts: z.array(CohortSelectorSchema).min(1),
  chartType: ChartTypeSchema,
  metric: DashboardMetricSchema,
  range: ChartRangeSchema.optional(),
});
export type DashboardConfig = z.infer<typeof DashboardConfigSchema>;

/** Who can open a saved chart: its creator and Admins, or everyone signed in. */
export const ChartVisibilitySchema = z.enum(["private", "everyone"]);
export type ChartVisibility = z.infer<typeof ChartVisibilitySchema>;

export const DashboardSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().nullable(),
  config: DashboardConfigSchema,
  visibility: ChartVisibilitySchema,
  createdByUserId: z.string().nullable(),
  /** The creator's name, or their email when they have none. */
  createdBy: z.string().nullable(),
  /** Whether the creator was removed from the dashboard. Their name stays in `createdBy`. */
  creatorRemoved: z.boolean(),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type Dashboard = z.infer<typeof DashboardSchema>;

// Create-or-update payload: the driver generates id on create and sets the
// timestamps. The server action sets createdByUserId from the session and never
// trusts a client-supplied value; the driver stores it and visibility on create only.
export const DashboardInputSchema = z.object({
  id: z.string().optional(),
  name: z.string(),
  description: z.string().nullable(),
  config: DashboardConfigSchema,
  visibility: ChartVisibilitySchema,
  createdByUserId: z.string().nullable().optional(),
});
export type DashboardInput = z.infer<typeof DashboardInputSchema>;

// ---- Cohort projection outputs ----

// One value per cohort at the latest scan in scope (feeds bars / stacked-share / table).
export const CohortPointSchema = z.object({
  cohortKey: z.string(),                   // stable per selector: "tag:<id>", "package:<name>", "component:<id>", "local"
  label: z.string(),
  color: z.string(),                       // tag.color for tag cohorts; "" (neutral) otherwise
  value: z.number().min(0),                // occurrences (count) or fraction 0..1 (share)
  componentCount: z.number().int().nonnegative(),
  role: CohortRoleSchema.optional(),
});
export type CohortPoint = z.infer<typeof CohortPointSchema>;

// Points-over-time per cohort (feeds trend / stacked-share).
export const CohortSeriesSchema = z.object({
  cohortKey: z.string(),
  label: z.string(),
  color: z.string(),
  points: z.array(z.object({
    t: z.string(),
    value: z.number().min(0),
    added: z.array(z.string()).optional(),  // after a series' first point: repos whose first scan this is, when they have the cohort in it
  })),
  role: CohortRoleSchema.optional(),
});
export type CohortSeries = z.infer<typeof CohortSeriesSchema>;

// ---- Component row (repo detail table) ----
export const PackageCountsSchema = z.object({ occurrenceCount: z.number().int().nonnegative(), fileCount: z.number().int().nonnegative() });
export type PackageCounts = z.infer<typeof PackageCountsSchema>;

export const ComponentRowSchema = z.object({
  componentId: z.string(),
  kind: ComponentKind,
  scope: ComponentScope,
  packageName: z.string().nullable(),         // can be absent on root-local files
  displayName: z.string(),                     // exportName or tagName
  writtenNames: z.array(z.string()).optional(), // other names files render it under, most used first; absent when none
  disambiguator: z.string().nullable(),        // publicEntry (external) or filePath (local)
  version: z.string().nullable(),
  occurrenceCount: z.number().int().nonnegative(),
  fileCount: z.number().int().nonnegative(),
  usedIn: z.record(z.string(), PackageCountsSchema).optional(), // uses and files per package; absent when the scan records none
  deprecated: z.boolean(),
  tags: z.array(TagRefSchema).optional(),
});
export type ComponentRow = z.infer<typeof ComponentRowSchema>;

// ---- Package summary (Packages tab) ----
export const PackageSummarySchema = z.object({
  packageName: z.string(),
  consumerCount: z.number().int().nonnegative(),
  componentCount: z.number().int().nonnegative(),
  totalOccurrences: z.number().int().nonnegative(),
  deprecatedCount: z.number().int().nonnegative(),
  distinctVersionCount: z.number().int().nonnegative(),
  // The one version in use when distinctVersionCount === 1; null when fragmented
  // (multiple versions) or unversioned (workspace-local packages).
  soleVersion: z.string().nullable(),
  tags: z.array(TagRefSchema).optional(),
});
export type PackageSummary = z.infer<typeof PackageSummarySchema>;

// ---- Package detail (per-package page) ----
export const PackageRepoVersionCellSchema = z.object({
  repoId: z.string(),
  version: z.string().nullable(),
  occurrenceCount: z.number().int().nonnegative(),
  committedAt: z.string(),
});
export type PackageRepoVersionCell = z.infer<typeof PackageRepoVersionCellSchema>;

export const PackageComponentRowSchema = z.object({
  componentId: z.string(),
  displayName: z.string(),
  kind: ComponentKind,
  totalOccurrences: z.number().int().nonnegative(),
  consumerCount: z.number().int().nonnegative(),
  deprecated: z.boolean(),
  // Strongest usage observed across repos: `strongerUsage` picks
  // "used somewhere" over "none" when the same id spans repos.
  usage: UsageKind,
});
export type PackageComponentRow = z.infer<typeof PackageComponentRowSchema>;

export const PackageDetailSchema = PackageSummarySchema.extend({
  cells: z.array(PackageRepoVersionCellSchema),
  components: z.array(PackageComponentRowSchema),
});
export type PackageDetail = z.infer<typeof PackageDetailSchema>;

// ---- Component summary (Components tab) ----
export const ComponentSummarySchema = z.object({
  componentId: z.string(),
  kind: ComponentKind,
  displayName: z.string(),
  packageName: z.string().nullable(),
  scope: ComponentScope,
  totalOccurrences: z.number().int().nonnegative(),
  repoCount: z.number().int().nonnegative(),
  repoId: z.string().nullable(),   // sole repo when repoCount === 1; null when it spans many
  deprecated: z.boolean(),
  tags: z.array(TagRefSchema).optional(),
  // Strongest usage observed across repos: see PackageComponentRow.
  usage: UsageKind,
});
export type ComponentSummary = z.infer<typeof ComponentSummarySchema>;

// ---- Governance (web-authored deprecation / supersession) ----
export const DispositionSchema = z.discriminatedUnion("kind", [
  z.object({
    kind: z.literal("superseded"),
    by: z.object({ packageName: z.string(), exportName: z.string().optional() }),
  }),
  z.object({ kind: z.literal("retired"), reason: z.string() }),
]);
export type Disposition = z.infer<typeof DispositionSchema>;

export const GovernanceRecordSchema = z.object({
  id: z.string(),
  grain: z.enum(["package", "component"]),
  targetPackage: z.string(),
  targetExport: z.string().nullable(), // exportName/tagName for component grain; null = whole package
  disposition: DispositionSchema,
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type GovernanceRecord = z.infer<typeof GovernanceRecordSchema>;

export const GovernanceInputSchema = z.object({
  id: z.string().optional(),
  grain: z.enum(["package", "component"]),
  targetPackage: z.string(),
  targetExport: z.string().nullable(),
  disposition: DispositionSchema,
});
export type GovernanceInput = z.infer<typeof GovernanceInputSchema>;

export const MigrationStatusSchema = z.discriminatedUnion("status", [
  z.object({ status: z.literal("active") }),
  z.object({
    status: z.literal("superseded"),
    by: z.object({ packageName: z.string(), exportName: z.string().optional() }),
  }),
  z.object({ status: z.literal("retired"), reason: z.string() }),
]);
export type MigrationStatus = z.infer<typeof MigrationStatusSchema>;

// ---- Component detail (per-repo drilldown page) ----
export const WrittenValueSchema = z.object({
  value: z.string(),
  count: z.number().int().nonnegative(),
});
export type WrittenValue = z.infer<typeof WrittenValueSchema>;

export const ReferenceSourceSchema = z.object({
  ref: z.string(),
  count: z.number().int().nonnegative(),
});
export type ReferenceSource = z.infer<typeof ReferenceSourceSchema>;

export const DeclaredMetaSchema = z.object({
  type: z.string().nullable(),
  required: z.boolean().nullable(),
  default: z.string().nullable(),
});
export type DeclaredMeta = z.infer<typeof DeclaredMetaSchema>;

export const PropUsageSchema = z.object({
  name: z.string(),
  written: z.array(WrittenValueSchema),
  references: z.array(ReferenceSourceSchema),
  dynamicCount: z.number().int().nonnegative(),
  omittedCount: z.number().int().nonnegative(),
  truncatedWrittenCount: z.number().int().nonnegative().default(0),
  status: z.enum(["used", "unused", "undeclared"]).nullable(),
  declared: DeclaredMetaSchema.nullable(),
});
export type PropUsage = z.infer<typeof PropUsageSchema>;

export const EventUsageSchema = z.object({
  name: z.string(),
  boundCount: z.number().int().nonnegative(),
});
export type EventUsage = z.infer<typeof EventUsageSchema>;

export const CompositionEdgeSchema = z.object({
  componentId: z.string(),
  displayName: z.string(),
  packageName: z.string().nullable(),
  scope: ComponentScope,
  count: z.number().int().nonnegative(),
});
export type CompositionEdge = z.infer<typeof CompositionEdgeSchema>;

export const OccurrencePropChipSchema = z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("literal"), name: z.string(), value: z.string() }),
  z.object({ kind: z.literal("reference"), name: z.string(), ref: z.string() }),
  z.object({ kind: z.literal("dynamic"), name: z.string() }),
]);
export type OccurrencePropChip = z.infer<typeof OccurrencePropChipSchema>;

export const OccurrenceRowSchema = z.object({
  occurrenceId: z.string(),
  filePath: z.string(),
  line: z.number().int().nonnegative(),
  column: z.number().int().nonnegative(),
  credit: z.custom<Credit>(),
  trace: z.custom<TraceStep[]>(),
  /** The name the file renders the component under, when it differs from the component's display name. */
  writtenName: z.string().optional(),
  /** The component whose code contains this call; absent when the call is outside any component. */
  owner: z.object({ componentId: z.string(), displayName: z.string() }).optional(),
  /** The package the call's file sits in; absent when the scan covers one package. */
  usedIn: z.string().optional(),
  props: z.array(OccurrencePropChipSchema),
  events: z.array(z.string()).default([]),
});
export type OccurrenceRow = z.infer<typeof OccurrenceRowSchema>;

export const ComponentSummaryBandSchema = z.object({
  footprint: z.object({
    callCount: z.number().int().nonnegative(),
    fileCount: z.number().int().nonnegative(),
    rendersCount: z.number().int().nonnegative(),
    renderedByCount: z.number().int().nonnegative(),
  }),
  apiUsage: z.object({
    declaredCount: z.number().int().nonnegative(),
    usedCount: z.number().int().nonnegative(),
    neverUsedCount: z.number().int().nonnegative(),
    undeclaredCount: z.number().int().nonnegative(),
  }),
  provenance: z.object({
    written: z.number().int().nonnegative(),
    reference: z.number().int().nonnegative(),
    dynamic: z.number().int().nonnegative(),
  }),
});
export type ComponentSummaryBand = z.infer<typeof ComponentSummaryBandSchema>;

export const ComponentDetailSchema = z.object({
  componentId: z.string(),
  repoId: z.string(),
  displayName: z.string(),
  packageName: z.string().nullable(),
  /** The package export's public entry; null for a repository declaration or a tag. */
  publicEntry: z.string().nullable(),
  scope: ComponentScope,
  kind: ComponentKind,
  version: z.string().nullable(),
  deprecated: z.boolean(),
  hasDeclaredApi: z.boolean(),
  hasRest: z.boolean(),
  migrationStatus: MigrationStatusSchema,
  /** The record that governs this identity, for the edge back to /governance. Null when ungoverned. */
  governedByRecordId: z.string().nullable(),
  definedAt: z
    .object({
      filePath: z.string(),
      line: z.number().int().nonnegative(),
      column: z.number().int().nonnegative(),
    })
    .nullable(),
  props: z.array(PropUsageSchema),
  events: z.array(EventUsageSchema).default([]),
  composition: z.object({
    renders: z.array(CompositionEdgeSchema),
    renderedBy: z.array(CompositionEdgeSchema),
    isRootCount: z.number().int().nonnegative(),
    isLeafCount: z.number().int().nonnegative(),
  }),
  occurrences: z.array(OccurrenceRowSchema),
  summary: ComponentSummaryBandSchema,
});
export type ComponentDetail = z.infer<typeof ComponentDetailSchema>;
export type ComponentDetailHead = Omit<ComponentDetail, "occurrences">;

// ---- Cross-repo component detail (per-component, aggregated across repos) ----
export const CrossRepoUsageSchema = z.object({
  repoId: z.string(),
  version: z.string().nullable(),
  occurrenceCount: z.number().int().nonnegative(),
  deprecated: z.boolean(),
  committedAt: z.string(),
});
export type CrossRepoUsage = z.infer<typeof CrossRepoUsageSchema>;

export const CrossRepoComponentDetailSchema = z.object({
  componentId: z.string(),
  packageName: z.string().nullable(),
  displayName: z.string(),
  kind: ComponentKind,
  scope: ComponentScope,
  repoCount: z.number().int().nonnegative(),
  totalOccurrences: z.number().int().nonnegative(),
  distinctVersionCount: z.number().int().nonnegative(),
  deprecatedAnywhere: z.boolean(),
  migrationStatus: MigrationStatusSchema,
  /** The record that governs this identity, for the edge back to /governance. Null when ungoverned. */
  governedByRecordId: z.string().nullable(),
  usages: z.array(CrossRepoUsageSchema),
});
export type CrossRepoComponentDetail = z.infer<typeof CrossRepoComponentDetailSchema>;
