// Generated by unplugin-vue-components

export {}

declare module 'vue' {
  export interface GlobalComponents {
    KitButton: typeof import('@example/vue-kit/es')['KitButton']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
  }
}
