// generated by unplugin-vue-components
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KitButton: typeof import('@example/vue-kit/es')['KitButton']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
  }
}
