name: Build and deploy docs
description: Build the Docusaurus site and deploy it to GitHub Pages

outputs:
  page_url:
    description: Deployed GitHub Pages URL
    value: ${{ steps.deployment.outputs.page_url }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 24.18.0
    - run: corepack enable
      shell: bash
    - run: yarn install --immutable
      shell: bash
    - run: yarn turbo run build --filter=@scoutui/docs
      shell: bash
    - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0
    - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        path: apps/docs/build
    - id: deployment
      uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
