import { mkdirSync, mkdtempSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  type CorepackPlan,
  findLockfile,
  type InstallPlan,
  installPlan,
  type Lockfile,
  type NpmPlan,
  packageManagerCommand,
  readPackageManager,
} from "../../../src/backfill/install.js";

const PACKAGE_LOCK = '{\n  "name": "lockfile-probe",\n  "lockfileVersion": 3,\n  "requires": true,\n';
const YARN_CLASSIC = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n\n\n";
const PNPM_5_4 = "lockfileVersion: 5.4\n\nspecifiers:\n  picomatch: 4.0.4\n\ndependencies:\n  picomatch: 4.0.4\n";
const PNPM_HASHED =
  "pnpm@9.15.9+sha512.2bc871c7009ad052b61c30dd89a37ee5f0c75a95f92f17be0eaf77ff61b561bb373db5550c541da0b71db51220603627bb94b0d1bb1fe38dd1991c70bb3fec74";

function yarnBerryLock(version: number, cacheKey: string): string {
  return `# This file is generated by running "yarn install" inside your project.\n# Manual changes might be lost - proceed with caution!\n\n__metadata:\n  version: ${version}\n  cacheKey: ${cacheKey}\n\n`;
}

function pnpmLock(version: string): string {
  return `lockfileVersion: '${version}'\n\nsettings:\n  autoInstallPeers: true\n  excludeLinksFromLockfile: false\n\n`;
}

const NPM_PLAN: NpmPlan = {
  manager: "npm",
  install: ["ci", "--ignore-scripts", "--no-audit", "--no-fund"],
  nuxtPrepare: ["exec", "--", "nuxt", "prepare"],
  label: "npm ci",
};

function yarnClassicPlan(spec: string): CorepackPlan {
  return {
    manager: "yarn",
    spec,
    install: ["install", "--frozen-lockfile", "--ignore-scripts", "--ignore-engines", "--non-interactive"],
    nuxtPrepare: ["nuxt", "prepare"],
    label: "yarn install",
  };
}

function yarnBerryPlan(spec: string): CorepackPlan {
  return {
    manager: "yarn",
    spec,
    install: ["install", "--immutable", "--mode=skip-build"],
    nuxtPrepare: ["nuxt", "prepare"],
    label: "yarn install",
  };
}

function pnpmPlan(spec: string): CorepackPlan {
  return {
    manager: "pnpm",
    spec,
    install: ["install", "--frozen-lockfile", "--ignore-scripts"],
    nuxtPrepare: ["exec", "nuxt", "prepare"],
    label: "pnpm install",
  };
}

describe("installPlan", () => {
  it.each<[string, Lockfile["name"], string, string | undefined, InstallPlan]>([
    ["installs a package-lock.json with npm ci, whatever packageManager says", "package-lock.json", PACKAGE_LOCK, "npm@10.9.2", NPM_PLAN],
    ["installs a Yarn 1 lockfile with Yarn 1.22.22 when there's no packageManager", "yarn.lock", YARN_CLASSIC, undefined, yarnClassicPlan("yarn@1.22.22")],
    ["installs a Yarn 1 lockfile with the Yarn 1 packageManager names", "yarn.lock", YARN_CLASSIC, "yarn@1.22.19", yarnClassicPlan("yarn@1.22.19")],
    ["installs a Yarn lockfile with __metadata version 8 with the Yarn packageManager names", "yarn.lock", yarnBerryLock(8, "10"), "yarn@4.12.0", yarnBerryPlan("yarn@4.12.0")],
    ["installs a Yarn lockfile with __metadata version 4 and no packageManager with Yarn 3.0.2", "yarn.lock", yarnBerryLock(4, "8"), undefined, yarnBerryPlan("yarn@3.0.2")],
    ["installs a Yarn lockfile with __metadata version 5 and no packageManager with Yarn 3.1.1", "yarn.lock", yarnBerryLock(5, "8"), undefined, yarnBerryPlan("yarn@3.1.1")],
    ["installs a Yarn lockfile with __metadata version 6 and no packageManager with Yarn 3.8.7", "yarn.lock", yarnBerryLock(6, "8"), undefined, yarnBerryPlan("yarn@3.8.7")],
    ["installs a Yarn lockfile with __metadata version 8 and no packageManager with Yarn 4.13.0", "yarn.lock", yarnBerryLock(8, "10c0"), undefined, yarnBerryPlan("yarn@4.13.0")],
    ["installs a Yarn lockfile with __metadata version 9 and no packageManager with Yarn 4.14.1", "yarn.lock", yarnBerryLock(9, "10c0"), undefined, yarnBerryPlan("yarn@4.14.1")],
    ["installs a Yarn lockfile with __metadata version 10 and no packageManager with Yarn 4.18.1", "yarn.lock", yarnBerryLock(10, "10c0"), undefined, yarnBerryPlan("yarn@4.18.1")],
    ["installs a Yarn lockfile with an __metadata version it doesn't list with the newest Yarn it lists", "yarn.lock", yarnBerryLock(11, "10c0"), undefined, yarnBerryPlan("yarn@4.18.1")],
    ["installs a pnpm 9.0 lockfile with the pnpm packageManager names, hash included", "pnpm-lock.yaml", pnpmLock("9.0"), PNPM_HASHED, pnpmPlan(PNPM_HASHED)],
    ["installs a pnpm 5.4 lockfile with no packageManager with pnpm 7.33.7", "pnpm-lock.yaml", PNPM_5_4, undefined, pnpmPlan("pnpm@7.33.7")],
    ["installs a pnpm 6.0 lockfile with no packageManager with pnpm 8.15.9", "pnpm-lock.yaml", pnpmLock("6.0"), undefined, pnpmPlan("pnpm@8.15.9")],
    ["installs a pnpm 9.0 lockfile with no packageManager with pnpm 12.8.1", "pnpm-lock.yaml", pnpmLock("9.0"), undefined, pnpmPlan("pnpm@12.8.1")],
    ["ignores a packageManager that names another manager", "yarn.lock", YARN_CLASSIC, "pnpm@9.15.9", yarnClassicPlan("yarn@1.22.22")],
  ])("%s", (_title, lockfile, head, packageManager, plan) => {
    expect(installPlan(lockfile, head, packageManager)).toStrictEqual(plan);
  });
});

describe("findLockfile", () => {
  let base: string;

  beforeEach(() => {
    base = realpathSync(mkdtempSync(join(tmpdir(), "scout-lockfile-")));
  });
  afterEach(() => {
    rmSync(base, { recursive: true, force: true });
  });

  function write(path: string, text = ""): void {
    mkdirSync(dirname(join(base, path)), { recursive: true });
    writeFileSync(join(base, path), text);
  }

  it("takes the lockfile in the nearest folder above the config's folder", () => {
    write("repo/yarn.lock");
    write("repo/apps/package-lock.json");
    mkdirSync(join(base, "repo/apps/web"));
    expect(findLockfile(join(base, "repo/apps/web"), join(base, "repo"))).toEqual({
      dir: join(base, "repo/apps"),
      name: "package-lock.json",
    });
  });

  it("takes the lockfile in the config's folder when that is the root", () => {
    write("repo/pnpm-lock.yaml");
    expect(findLockfile(join(base, "repo"), join(base, "repo"))).toEqual({ dir: join(base, "repo"), name: "pnpm-lock.yaml" });
  });

  it("looks no further up than the root", () => {
    write("yarn.lock");
    mkdirSync(join(base, "repo/apps/web"), { recursive: true });
    expect(findLockfile(join(base, "repo/apps/web"), join(base, "repo"))).toBeNull();
  });

  it.each<[string, Record<string, string>, Lockfile["name"]]>([
    ["takes yarn.lock over package-lock.json when there is no packageManager", { name: "example-web" }, "yarn.lock"],
    ["takes the lockfile of the manager packageManager names", { name: "example-web", packageManager: "npm@10.9.2" }, "package-lock.json"],
  ])("with two lockfiles in one folder, %s", (_title, manifest, name) => {
    write("repo/package.json", JSON.stringify(manifest));
    write("repo/yarn.lock");
    write("repo/package-lock.json");
    expect(findLockfile(join(base, "repo"), join(base, "repo"))).toEqual({ dir: join(base, "repo"), name });
  });
});

describe("readPackageManager", () => {
  let dir: string;

  beforeEach(() => {
    dir = realpathSync(mkdtempSync(join(tmpdir(), "scout-package-manager-")));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  it.each<[string, Record<string, unknown>, string | undefined]>([
    [
      "takes packageManager over devEngines.packageManager",
      { packageManager: "pnpm@9.15.9", devEngines: { packageManager: { name: "pnpm", version: "^10.0.0" } } },
      "pnpm@9.15.9",
    ],
    [
      "takes the version devEngines.packageManager gives the lockfile's manager, as written",
      { devEngines: { packageManager: { name: "pnpm", version: "^9.0.0" } } },
      "pnpm@^9.0.0",
    ],
    [
      "takes the devEngines.packageManager entry that names the lockfile's manager from a list",
      {
        devEngines: {
          packageManager: [
            { name: "yarn", version: "4.12.0" },
            { name: "pnpm", version: "^9.0.0", onFail: "error" },
          ],
        },
      },
      "pnpm@^9.0.0",
    ],
    [
      "ignores a devEngines.packageManager entry that names another manager",
      { devEngines: { packageManager: { name: "yarn", version: "4.12.0" } } },
      undefined,
    ],
    [
      "ignores a devEngines.packageManager entry with no version",
      { devEngines: { packageManager: { name: "pnpm", onFail: "error" } } },
      undefined,
    ],
  ])("%s", (_title, manifest, packageManager) => {
    writeFileSync(join(dir, "package.json"), JSON.stringify({ name: "example-web", ...manifest }));
    expect(readPackageManager({ dir, name: "pnpm-lock.yaml" })).toBe(packageManager);
  });
});

describe("packageManagerCommand", () => {
  const corepack = { script: "/run/tools/node_modules/corepack/dist/corepack.js" };

  it.each<
    [
      string,
      Parameters<typeof packageManagerCommand>[0],
      "install" | "nuxtPrepare",
      { command: string; args: string[] },
    ]
  >([
    [
      "runs npm's install with the user's own npm",
      NPM_PLAN,
      "install",
      { command: "npm", args: ["ci", "--ignore-scripts", "--no-audit", "--no-fund"] },
    ],
    [
      "runs npm's nuxt prepare with the user's own npm",
      NPM_PLAN,
      "nuxtPrepare",
      { command: "npm", args: ["exec", "--", "nuxt", "prepare"] },
    ],
    [
      "runs Yarn's install through the fetched Corepack with the Node running Scout",
      { ...yarnBerryPlan("yarn@4.12.0"), corepack },
      "install",
      { command: process.execPath, args: [corepack.script, "yarn@4.12.0", "install", "--immutable", "--mode=skip-build"] },
    ],
    [
      "runs pnpm's nuxt prepare through the fetched Corepack with the Node running Scout",
      { ...pnpmPlan("pnpm@12.8.1"), corepack },
      "nuxtPrepare",
      { command: process.execPath, args: [corepack.script, "pnpm@12.8.1", "exec", "nuxt", "prepare"] },
    ],
  ])("%s", (_title, plan, step, command) => {
    expect(packageManagerCommand(plan, step)).toStrictEqual(command);
  });
});
