{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace (include "scout.postgresqlSecretName" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scout.postgresqlSecretName" . }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "scout.postgresqlSelectorLabels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.postgresql.auth.passwordKey }}: {{ if $secret }}{{ index $secret.data .Values.postgresql.auth.passwordKey }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- end }}
